name: Test Backend

on: 
  push:
    branches:
    - master
    - development 
  pull_request:
    branches:
    - master
    - development

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - uses: Harmon758/postgresql-action@v1.0.0
      name: Setup PostgreSQL
      with:
        postgresql version: 12.1
        postgresql db: ${{ secrets.DATABASE_NAME }}
        postgresql user: ${{ secrets.DATABASE_USER }}
        postgresql password: ${{ secrets.DATABASE_PASSWORD }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python backend/setup.py develop
    
    - name: Test with pytest
      run: |
        PYTHONPATH=${PYTHONPATH}:/home/runner/work/Todolist/Todolist/backend:$(pwd)
        export TESTING_DATABASE_URI=${{ secrets.TESTING_DATABASE_URI }}
        export SECRET_KEY=${{ secrets.SECRET_KEY }}
        pytest
